2023-11-22 16:43:12,956 INFO    MainThread:12084 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-22 16:43:12,956 INFO    MainThread:12084 [wandb_setup.py:_flush():76] Configure stats pid to 12084
2023-11-22 16:43:12,963 INFO    MainThread:12084 [wandb_setup.py:_flush():76] Loading settings from C:\Users\COMPUTOCKS\.config\wandb\settings
2023-11-22 16:43:12,963 INFO    MainThread:12084 [wandb_setup.py:_flush():76] Loading settings from C:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\settings
2023-11-22 16:43:12,963 INFO    MainThread:12084 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'EstrogenReceptor_FeedForwardNN'}
2023-11-22 16:43:12,963 INFO    MainThread:12084 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'FFNN.py', 'program_abspath': 'c:\\Users\\COMPUTOCKS\\Desktop\\semestre_5\\machine_learning\\FFNN.py', 'program': 'c:/Users/COMPUTOCKS/Desktop/semestre_5/machine_learning/FFNN.py'}
2023-11-22 16:43:12,966 INFO    MainThread:12084 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\run-20231122_164312-ac4y3ibb\logs\debug.log
2023-11-22 16:43:12,966 INFO    MainThread:12084 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\run-20231122_164312-ac4y3ibb\logs\debug-internal.log
2023-11-22 16:43:12,966 INFO    MainThread:12084 [wandb_init.py:init():564] calling init triggers
2023-11-22 16:43:12,966 INFO    MainThread:12084 [wandb_init.py:init():572] wandb.init called with sweep_config: {}
config: {'epochs': 1000, 'batch_size': 10, 'learning_rate': 0.0001, 'weight_decay': 0.025, 'patience': 5, 'delta_earlyStopping': 0.001}
2023-11-22 16:43:12,966 INFO    MainThread:12084 [wandb_init.py:init():614] starting backend
2023-11-22 16:43:12,966 INFO    MainThread:12084 [wandb_init.py:init():618] setting up manager
2023-11-22 16:43:12,976 INFO    MainThread:12084 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=spawn, using: spawn
2023-11-22 16:43:12,984 INFO    MainThread:12084 [wandb_init.py:init():624] backend started and connected
2023-11-22 16:43:13,005 INFO    MainThread:12084 [wandb_init.py:init():716] updated telemetry
2023-11-22 16:43:13,179 INFO    MainThread:12084 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-11-22 16:43:13,588 INFO    MainThread:12084 [wandb_run.py:_on_init():2254] communicating current version
2023-11-22 16:43:13,810 INFO    MainThread:12084 [wandb_run.py:_on_init():2263] got version response 
2023-11-22 16:43:13,810 INFO    MainThread:12084 [wandb_init.py:init():800] starting run threads in backend
2023-11-22 16:43:14,062 INFO    MainThread:12084 [wandb_run.py:_console_start():2233] atexit reg
2023-11-22 16:43:14,062 INFO    MainThread:12084 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2023-11-22 16:43:14,062 INFO    MainThread:12084 [wandb_run.py:_redirect():2153] Wrapping output streams.
2023-11-22 16:43:14,062 INFO    MainThread:12084 [wandb_run.py:_redirect():2178] Redirects installed.
2023-11-22 16:43:14,064 INFO    MainThread:12084 [wandb_init.py:init():841] run started, returning control to user process
2023-11-22 16:43:40,734 INFO    MainThread:12084 [pyagent.py:run():316] Starting sweep agent: entity=None, project=None, count=5
2023-11-22 16:43:48,376 WARNING MsgRouterThr:12084 [router.py:message_loop():77] message_loop has been closed
2023-11-22 16:43:53,659 INFO    Thread-12 :12084 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-22 16:43:53,659 INFO    Thread-12 :12084 [wandb_setup.py:_flush():76] Configure stats pid to 12084
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_setup.py:_flush():76] Loading settings from C:\Users\COMPUTOCKS\.config\wandb\settings
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_setup.py:_flush():76] Loading settings from C:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\settings
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'EstrogenReceptor_FeedForwardNN', 'entity': 'simios', 'root_dir': 'C:\\Users\\COMPUTOCKS\\Desktop\\semestre_5\\machine_learning', 'sweep_id': '1ln0ht9a', 'run_id': 'dirw27l1', 'sweep_param_path': 'C:\\Users\\COMPUTOCKS\\Desktop\\semestre_5\\machine_learning\\wandb\\sweep-1ln0ht9a\\config-dirw27l1.yaml'}
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'FFNN.py', 'program_abspath': 'c:\\Users\\COMPUTOCKS\\Desktop\\semestre_5\\machine_learning\\FFNN.py', 'program': 'c:/Users/COMPUTOCKS/Desktop/semestre_5/machine_learning/FFNN.py'}
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\run-20231122_164353-dirw27l1\logs\debug.log
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\run-20231122_164353-dirw27l1\logs\debug-internal.log
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_init.py:init():564] calling init triggers
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_init.py:init():572] wandb.init called with sweep_config: {'batch_size': 54.72573560016053, 'delta_es': 0.04695427879562177, 'epochs': 2000, 'learning_rate': 0.006583385712919347, 'patience': 24.94587386370909, 'weight_decay_opt': 0.02852564520499406}
config: {'epochs': 1000, 'batch_size': 10, 'learning_rate': 0.0001, 'weight_decay': 0.025, 'patience': 5, 'delta_earlyStopping': 0.001}
2023-11-22 16:43:53,661 INFO    Thread-12 :12084 [wandb_init.py:init():609] wandb.init() called when a run is still active
2023-11-22 16:43:53,884 ERROR   Thread-12 :12084 [wandb_init.py:init():1194] error
Traceback (most recent call last):
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_init.py", line 1166, in init
    run = wi.init()
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_init.py", line 611, in init
    tel.feature.init_return_run = True
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_run.py", line 758, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_run.py", line 769, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\lib\sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\COMPUTOCKS\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
